---
ldap_domain: "lab.local"
ldap_base_dn: "dc=lab,dc=local"
ldap_admin_cn: "admin"
ldap_admin_dn: "cn=admin,dc=lab,dc=local"
ldap_admin_password: "admin123"

ldap_packages:
  - openldap
  - openldap-servers
  - openldap-clients


ldap_users:
  - uid: john
    cn: John Doe
    sn: Doe
    uidNumber: 10001
    gidNumber: 10001
    password: password123

  - uid: sarah
    cn: Sarah Lee
    sn: Lee
    uidNumber: 10002
    gidNumber: 10002
    password: password123

  - uid: devops1
    cn: DevOps One
    sn: DevOps
    uidNumber: 10003
    gidNumber: 10003
    password: password123

ldap_groups:
  - name: admins
    gid: 20001
    members:
      - john

  - name: devops
    gid: 20002
    members:
      - devops1

  - name: developers
    gid: 20003
    members:
      - sarah

