---
- name: Ensure EPEL repository is present
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install Node Exporter
  ansible.builtin.dnf:
    name: node_exporter
    state: present

- name: Ensure Node Exporter is started
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true

- name: Open Firewall Port 9100 (ignore if firewalld not running)
  ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: yes
