---
- name: Ensure EPEL repository is present
  ansible.builtin.dnf:
    name: epel-release
    state: present
  become: true

- name: Install Node Exporter from EPEL
  ansible.builtin.dnf:
    name: node_exporter
    state: present
  become: true

- name: Ensure Node Exporter service is enabled and started
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
  become: true

- name: Open Firewall Port 9100
  ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true
