- name: Generate admin password hash
  command: slappasswd -s {{ ldap_admin_password }}
  register: ldap_password_hash
  changed_when: false

- name: Create config LDIF
  template:
    src: config.ldif.j2
    dest: /tmp/config.ldif

- name: Apply LDAP config
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/config.ldif
  notify: restart slapd
