- name: Create groups LDIF
  template:
    src: groups.ldif.j2
    dest: /tmp/groups.ldif

- name: Apply groups
  command: >
    ldapadd -x -D "{{ ldap_admin_dn }}"
    -w "{{ ldap_admin_password }}"
    -f /tmp/groups.ldif
  register: group_add
  failed_when:
    - group_add.rc != 0
    - "'Already exists' not in group_add.stderr"
