- name: Load cosine schema
  ansible.builtin.command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
  register: cosine_schema
  failed_when:
    - cosine_schema.rc != 0
    - "'already exists' not in cosine_schema.stderr"
    - "'Duplicate attributeType' not in cosine_schema.stderr"
    - "'error (80)' not in cosine_schema.stderr"
  changed_when: cosine_schema.rc == 0

- name: Load nis schema
  ansible.builtin.command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
  register: nis_schema
  failed_when:
    - nis_schema.rc != 0
    - "'already exists' not in nis_schema.stderr"
    - "'Duplicate attributeType' not in nis_schema.stderr"
    - "'error (80)' not in nis_schema.stderr"
  changed_when: nis_schema.rc == 0

- name: Load inetorgperson schema
  ansible.builtin.command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif
  register: inet_schema
  failed_when:
    - inet_schema.rc != 0
    - "'already exists' not in inet_schema.stderr"
    - "'Duplicate attributeType' not in inet_schema.stderr"
    - "'error (80)' not in inet_schema.stderr"
  changed_when: inet_schema.rc == 0
