- name: Ensure cert directory exists
  file:
    path: /etc/openldap/certs
    state: directory

- name: Fix permissions
  file:
    path: /etc/openldap/certs
    recurse: yes
    owner: ldap
    group: ldap
