ldap_admin_password: "Oracle@power22"

ldap_users:
  - uid: testuser
    cn: Test User
    sn: User
    uidNumber: 10001
    gidNumber: 10001
    password: password123

  - uid: devuser
    cn: Dev User
    sn: User
    uidNumber: 10002
    gidNumber: 10002
    password: password123

ldap_groups:
  - name: developers
    gid: 10001
